package redis

import "github.com/c-bata/go-prompt"

var redisCMDSuggest = []prompt.Suggest{
	{Text: "SLAVEOF", Description: "SLAVEOF host port"},
	{Text: "DEBUG", Description: ""},
	{Text: "PFDEBUG", Description: "PFDEBUG"},
	{Text: "PFSELFTEST", Description: "PFSELFTEST"},
	{Text: "FAILOVER", Description: "FAILOVER [TO host port [FORCE]] [ABORT] [TIMEOUT milliseconds]"},
	{Text: "LATENCY", Description: ""},
	{Text: "MONITOR", Description: "MONITOR"},
	{Text: "PSYNC", Description: "PSYNC replicationid offset"},
	{Text: "REPLICAOF", Description: "REPLICAOF host port"},
	{Text: "ACL", Description: ""},
	{Text: "BGREWRITEAOF", Description: "BGREWRITEAOF"},
	{Text: "CLIENT", Description: ""},
	{Text: "SHUTDOWN", Description: "SHUTDOWN [NOSAVE|SAVE] [NOW] [FORCE] [ABORT]"},
	{Text: "SYNC", Description: "SYNC"},
	{Text: "SAVE", Description: "SAVE"},
	{Text: "BGSAVE", Description: "BGSAVE"},
	{Text: "MODULE", Description: ""},
	{Text: "REPLCONF", Description: "REPLCONF"},
	{Text: "CLUSTER", Description: ""},
	{Text: "CONFIG", Description: ""},
	{Text: "SLOWLOG", Description: "SLOWLOG subcommand [argument]"},
	{Text: "ZRANGE", Description: "ZRANGE key start stop [WITHSCORES]"},

	{Text: "GEOPOS", Description: "GEOPOS key member [member ...]"},
	{Text: "GEODIST", Description: "GEODIST key member1 member2 [unit]"},
	{Text: "LINDEX", Description: "LINDEX key index"},
	{Text: "PUNSUBSCRIBE", Description: "PUNSUBSCRIBE [pattern ...]"},
	{Text: "SSCAN", Description: "SSCAN key cursor [MATCH pattern] [COUNT count]"},
	{Text: "TIME", Description: "TIME"},
	{Text: "ZLEXCOUNT", Description: "ZLEXCOUNT key min max"},
	{Text: "XPENDING", Description: "XPENDING key group [start end count] [consumer]"},
	{Text: "SMEMBERS", Description: "SMEMBERS key"},
	{Text: "TTL", Description: "TTL key"},
	{Text: "ZREVRANGE", Description: "ZREVRANGE key start stop [WITHSCORES]"},
	{Text: "HSTRLEN", Description: "HSTRLEN key field"},
	{Text: "XINFO", Description: "XINFO [CONSUMERS key groupname] [GROUPS key] [STREAM key] [HELP]"},
	{Text: "HGETALL", Description: "HGETALL key"},
	{Text: "PING", Description: "PING [message]"},
	{Text: "ROLE", Description: "ROLE"},
	{Text: "XREAD", Description: "XREAD [COUNT count] [BLOCK milliseconds] STREAMS key [key ...] ID [ID ...]"},
	{Text: "TYPE", Description: "TYPE key"},
	{Text: "XREVRANGE", Description: "XREVRANGE key end start [COUNT count]"},
	{Text: "XLEN", Description: "XLEN key"},
	{Text: "HSCAN", Description: "HSCAN key cursor [MATCH pattern] [COUNT count]"},
	{Text: "MULTI", Description: "MULTI"},
	{Text: "SCARD", Description: "SCARD key"},
	{Text: "ZRANGEBYLEX", Description: "ZRANGEBYLEX key min max [LIMIT offset count]"},
	{Text: "BITPOS", Description: "BITPOS key bit [start] [end]"},
	{Text: "KEYS", Description: "KEYS pattern"},
	{Text: "LRANGE", Description: "LRANGE key start stop"},
	{Text: "SDIFF", Description: "SDIFF key [key ...]"},
	{Text: "SUBSCRIBE", Description: "SUBSCRIBE channel [channel ...]"},
	{Text: "UNWATCH", Description: "UNWATCH"},
	{Text: "ZSCAN", Description: "ZSCAN key cursor [MATCH pattern] [COUNT count]"},
	{Text: "XREADGROUP", Description: "XREADGROUP GROUP group consumer [COUNT count] [BLOCK milliseconds] [NOACK] STREAMS key [key ...] ID [ID ...]"},
	{Text: "EXEC", Description: "EXEC"},
	{Text: "GETBIT", Description: "GETBIT key offset"},
	{Text: "PTTL", Description: "PTTL key"},
	{Text: "HKEYS", Description: "HKEYS key"},
	{Text: "HLEN", Description: "HLEN key"},
	{Text: "SCAN", Description: "SCAN cursor [MATCH pattern] [COUNT count]"},
	{Text: "STRLEN", Description: "STRLEN key"},
	{Text: "WATCH", Description: "WATCH key [key ...]"},
	{Text: "BITCOUNT", Description: "BITCOUNT key [start] [end]"},
	{Text: "DUMP", Description: "DUMP key"},
	{Text: "HGET", Description: "HGET key field"},
	{Text: "XRANGE", Description: "XRANGE key start end [COUNT count]"},
	{Text: "PUBSUB", Description: ""},
	{Text: "SUNION", Description: "SUNION key [key ...]"},
	{Text: "ZRANK", Description: "ZRANK key member"},
	{Text: "ECHO", Description: "ECHO message"},
	{Text: "EXISTS", Description: "EXISTS key"},
	{Text: "GETRANGE", Description: "GETRANGE key start end"},
	{Text: "GEOHASH", Description: "GEOHASH key member [member ...]"},
	{Text: "DISCARD", Description: "DISCARD"},
	{Text: "RANDOMKEY", Description: "RANDOMKEY"},
	{Text: "SELECT", Description: "SELECT index"},
	{Text: "BITOP", Description: "BITOP operation destkey key [key ...]"},
	{Text: "ZRANGEBYSCORE", Description: "ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]"},
	{Text: "ZREVRANGEBYSCORE", Description: "ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]"},
	{Text: "MGET", Description: "MGET key [key ...]"},
	{Text: "PSUBSCRIBE", Description: "PSUBSCRIBE pattern [pattern ...]"},
	{Text: "ZREVRANGEBYLEX", Description: "ZREVRANGEBYLEX key max min [LIMIT offset count]"},
	{Text: "HEXISTS", Description: "HEXISTS key field"},
	{Text: "INFO", Description: "INFO [section]"},
	{Text: "LLEN", Description: "LLEN key"},
	{Text: "ZREVRANK", Description: "ZREVRANK key member"},
	{Text: "ZSCORE", Description: "ZSCORE key member"},
	{Text: "AUTH", Description: "AUTH password"},
	{Text: "COMMAND", Description: ""},
	{Text: "HMGET", Description: "HMGET key field [field ...]"},
	{Text: "UNSUBSCRIBE", Description: "UNSUBSCRIBE [channel ...]"},
	{Text: "ZCARD", Description: "ZCARD key"},
	{Text: "DBSIZE", Description: "DBSIZE"},
	{Text: "GET", Description: "GET key"},
	{Text: "SISMEMBER", Description: "SISMEMBER key member"},
	{Text: "SRANDMEMBER", Description: "SRANDMEMBER key [count]"},
	{Text: "MEMORY", Description: ""},
	{Text: "HVALS", Description: "HVALS key"},
	{Text: "LASTSAVE", Description: "LASTSAVE"},
	{Text: "SINTER", Description: "SINTER key [key ...]"},
	{Text: "OBJECT", Description: ""},
	{Text: "ZCOUNT", Description: "ZCOUNT key min max"},
	{Text: "BZPOPMIN", Description: "BZPOPMIN key [key ...] timeout"},
	{Text: "UNLINK", Description: "UNLINK key [key ...]"},
	{Text: "ZREMRANGEBYSCORE", Description: "ZREMRANGEBYSCORE key min max"},
	{Text: "ZUNIONSTORE", Description: "ZUNIONSTORE destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM|MIN|MAX]"},
	{Text: "APPEND", Description: "APPEND key value"},
	{Text: "HDEL", Description: "HDEL key field [field ...]"},
	{Text: "LPUSHX", Description: "LPUSHX key value"},
	{Text: "PEXPIREAT", Description: "PEXPIREAT key milliseconds-timestamp"},
	{Text: "RPOPLPUSH", Description: "RPOPLPUSH source destination"},
	{Text: "SPOP", Description: "SPOP key"},
	{Text: "SWAPDB", Description: "SWAPDB index1 index2"},
	{Text: "XGROUP", Description: ""},
	{Text: "ZPOPMAX", Description: "ZPOPMAX key [count]"},
	{Text: "GEOADD", Description: "GEOADD key [NX|XX] [CH] longitude latitude member [longitude latitude member ...]"},
	{Text: "HINCRBY", Description: "HINCRBY key field increment"},
	{Text: "MSET", Description: "MSET key value [key value ...]"},
	{Text: "ZREMRANGEBYLEX", Description: "ZREMRANGEBYLEX key min max"},
	{Text: "DECRBY", Description: "DECRBY key decrement"},
	{Text: "SDIFFSTORE", Description: "SDIFFSTORE destination key [key ...]"},
	{Text: "ZINCRBY", Description: "ZINCRBY key increment member"},
	{Text: "ZINTERSTORE", Description: "ZINTERSTORE destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM|MIN|MAX]"},
	{Text: "ZPOPMIN", Description: "ZPOPMIN key [count]"},
	{Text: "EVAL", Description: "EVAL script numkeys key [key ...] arg [arg ...]"},
	{Text: "EXPIREAT", Description: "EXPIREAT key timestamp"},
	{Text: "INCR", Description: "INCR key"},
	{Text: "MSETNX", Description: "MSETNX key value [key value ...]"},
	{Text: "LINSERT", Description: "LINSERT key BEFORE|AFTER pivot value"},
	{Text: "PUBLISH", Description: "PUBLISH channel message"},
	{Text: "SINTERSTORE", Description: "SINTERSTORE destination key [key ...]"},
	{Text: "XDEL", Description: "XDEL key ID [ID ...]"},
	{Text: "ZREM", Description: "ZREM key member [member ...]"},
	{Text: "BRPOPLPUSH", Description: "BRPOPLPUSH source destination timeout"},
	{Text: "RPOP", Description: "RPOP key"},
	{Text: "SUNIONSTORE", Description: "SUNIONSTORE destination key [key ...]"},
	{Text: "XTRIM", Description: "XTRIM key MAXLEN [~] count"},
	{Text: "ZADD", Description: "ZADD key score member [score] [member]"},
	{Text: "ZREMRANGEBYRANK", Description: "ZREMRANGEBYRANK key start stop"},
	{Text: "BRPOP", Description: "BRPOP key [key ...] timeout"},
	{Text: "LPUSH", Description: "LPUSH key value [value ...]"},
	{Text: "LTRIM", Description: "LTRIM key start stop"},
	{Text: "SCRIPT", Description: ""},
	{Text: "SETEX", Description: "SETEX key seconds value"},
	{Text: "COPY", Description: "COPY source destination [DB destination-db] [REPLACE]"},
	{Text: "FLUSHALL", Description: "FLUSHALL"},
	{Text: "HMSET", Description: "HMSET key field value [field value ...]"},
	{Text: "INCRBY", Description: "INCRBY key increment"},
	{Text: "LSET", Description: "LSET key index value"},
	{Text: "RPUSH", Description: "RPUSH key value [value ...]"},
	{Text: "BLPOP", Description: "BLPOP key [key ...] timeout"},
	{Text: "SETBIT", Description: "SETBIT key offset value"},
	{Text: "SMOVE", Description: "SMOVE source destination member"},
	{Text: "RPUSHX", Description: "RPUSHX key value"},
	{Text: "SORT", Description: "SORT key [BY pattern] [LIMIT offset count] [GET pattern [GET pattern ...]] [ASC|DESC] [ALPHA] [STORE destination]"},
	{Text: "SADD", Description: "SADD key member [member ...]"},
	{Text: "SREM", Description: "SREM key member [member ...]"},
	{Text: "BLMOVE", Description: "BLMOVE source destination LEFT|RIGHT LEFT|RIGHT timeout"},
	{Text: "EVALSHA", Description: "EVALSHA sha1 numkeys key [key ...] arg [arg ...]"},
	{Text: "EXPIRE", Description: "EXPIRE key seconds"},
	{Text: "GETDEL", Description: "GETDEL key"},
	{Text: "HINCRBYFLOAT", Description: "HINCRBYFLOAT key field increment"},
	{Text: "HSET", Description: "HSET key field value"},
	{Text: "HSETNX", Description: "HSETNX key field value"},
	{Text: "LMOVE", Description: "LMOVE source destination LEFT|RIGHT LEFT|RIGHT"},
	{Text: "MIGRATE", Description: "MIGRATE host port key destination-db timeout"},
	{Text: "MOVE", Description: "MOVE key db"},
	{Text: "DECR", Description: "DECR key"},
	{Text: "GETSET", Description: "GETSET key value"},
	{Text: "LREM", Description: "LREM key count value"},
	{Text: "RENAME", Description: "RENAME key newkey"},
	{Text: "SETNX", Description: "SETNX key value"},
	{Text: "DEL", Description: "DEL key [key ...]"},
	{Text: "FLUSHDB", Description: "FLUSHDB"},
	{Text: "PERSIST", Description: "PERSIST key"},
	{Text: "PEXPIRE", Description: "PEXPIRE key milliseconds"},
	{Text: "RENAMENX", Description: "RENAMENX key newkey"},
	{Text: "ZDIFFSTORE", Description: "ZDIFFSTORE destination numkeys key [key ...]"},
	{Text: "ZRANGESTORE", Description: "ZRANGESTORE dst src min max [BYSCORE|BYLEX] [REV] [LIMIT offset count]"},
	{Text: "BZPOPMAX", Description: "BZPOPMAX key [key ...] timeout"},
	{Text: "INCRBYFLOAT", Description: "INCRBYFLOAT key increment"},
	{Text: "LPOP", Description: "LPOP key"},
	{Text: "PSETEX", Description: "PSETEX key milliseconds value"},
	{Text: "RESTORE", Description: "RESTORE key ttl serialized-value"},
	{Text: "SET", Description: "SET key value"},
	{Text: "SETRANGE", Description: "SETRANGE key offset value"},
	{Text: "XADD", Description: "XADD key ID field string [field string ...]"},
}
